### ISSUE TITLE
Submitting converted valid_all.json to IRS FIRE Test System results in error

### ISSUE THREAD

**Issue by gregsadetsky** [sdj0/fire-1099#9]
I ran fire-1099 on `valid_all.json` and submitted the resulting "ASCII file" to the IRS FIRE Test System. A day later, I've received the following:

```
Your file contains information that does not adhere to the current format requirements.
Refer to Publication 1220 or contact your software company or service provider for further information.
```

There's absolutely no information as to what field might be wrong... Any ideas?

Thanks!

**Comment by sdj0** [comment]
Hey @gregsadetsky - I'm not sure exactly what would be causing FIRE to reject the filing. As you suggest, the errors are extremely vague. It's possible that there's some additional validation not captured in the schema (e.g. restricting nonexistent numbers with a 555 area code, for example). I'm not actually able to try to replicate this since the FIRE test system seems to be erroring out when I enter my TCC and TIN. 

Since others have been able to successfully submit filings recently using these same schemas, I'm going to go ahead and close this issue. That said, I'd love to hear if you have any other recent data points on successful or failed submission attempts.

**Comment by gregsadetsky** [comment]
Hey, thanks for your reply! I haven't touched the project since that time, so unfortunately I nave no new data to contribute. Glad to hear that people were recently able to successfully file!
